SET(VPVIEW_VERSION_MAJOR ${VISGUI_VERSION_MAJOR})
SET(VPVIEW_VERSION_MINOR ${VISGUI_VERSION_MINOR})
SET(VPVIEW_VERSION_PATCH ${VISGUI_VERSION_PATCH})
SET(VPVIEW_VERSION_BUILD "master")

SET(VPVIEW_VERSION_STR "${VPVIEW_VERSION_MAJOR}.${VPVIEW_VERSION_MINOR}.${VPVIEW_VERSION_PATCH}-${VPVIEW_VERSION_BUILD}")

SET(VPVIEW_COPY_YEAR ${VISGUI_COPY_YEAR})
