set(VISGUI_VERSION_MAJOR 2)
set(VISGUI_VERSION_MINOR 2)
set(VISGUI_VERSION_PATCH 8)
set(VISGUI_VERSION_BUILD "master")

set(VISGUI_VERSION_STR "${VISGUI_VERSION_MAJOR}.${VISGUI_VERSION_MINOR}.${VISGUI_VERSION_PATCH}")

string(TIMESTAMP VISGUI_COPY_YEAR "%Y")
