set(VISGUI_VERSION_MAJOR 1)
set(VISGUI_VERSION_MINOR 0)
set(VISGUI_VERSION_PATCH 0)
set(VISGUI_VERSION_BUILD "master")

set(VISGUI_VERSION_STR "${VISGUI_VERSION_MAJOR}.${VISGUI_VERSION_MINOR}.${VISGUI_VERSION_PATCH}")

string(TIMESTAMP VISGUI_COPY_YEAR "%Y")
