SET(QTE_AMC_VERSION_MAJOR ${VISGUI_VERSION_MAJOR})
SET(QTE_AMC_VERSION_MINOR ${VISGUI_VERSION_MINOR})
SET(QTE_AMC_VERSION_PATCH ${VISGUI_VERSION_PATCH})

SET(QTE_AMC_VERSION_STR "${QTE_AMC_VERSION_MAJOR}.${QTE_AMC_VERSION_MINOR}.${QTE_AMC_VERSION_PATCH}")
