SET(VSPLAY_VERSION_MAJOR ${VISGUI_VERSION_MAJOR})
SET(VSPLAY_VERSION_MINOR ${VISGUI_VERSION_MINOR})
SET(VSPLAY_VERSION_PATCH ${VISGUI_VERSION_PATCH})
SET(VSPLAY_VERSION_BUILD ${VISGUI_VERSION_BUILD})

SET(VSPLAY_VERSION_STR "${VSPLAY_VERSION_MAJOR}.${VSPLAY_VERSION_MINOR}.${VSPLAY_VERSION_PATCH}-${VSPLAY_VERSION_BUILD}")

SET(VSPLAY_COPY_YEAR ${VISGUI_COPY_YEAR})
