SET(VIQUI_VERSION_MAJOR ${VISGUI_VERSION_MAJOR})
SET(VIQUI_VERSION_MINOR ${VISGUI_VERSION_MINOR})
SET(VIQUI_VERSION_PATCH ${VISGUI_VERSION_PATCH})
SET(VIQUI_VERSION_BUILD ${VISGUI_VERSION_BUILD})

SET(VIQUI_VERSION_STR "${VIQUI_VERSION_MAJOR}.${VIQUI_VERSION_MINOR}.${VIQUI_VERSION_PATCH}-${VIQUI_VERSION_BUILD}")

SET(VIQUI_COPY_YEAR ${VISGUI_COPY_YEAR})
